name: Publish packages

on:
  push:
    branches: [ "main" ]
    paths: [ "src/**", '**/build-and-deploy-packages.yml', 'Directory.Packages.props' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./
      
    - name: Run unit test
      run: dotnet test
      
    - name: Build
      run: dotnet pack
      working-directory: ./
      
    - name: publish-to-nuget
      run: dotnet nuget push ./**/*.nupkg --api-key=${{secrets.NUGET_KEY}} --skip-duplicate --source=https://api.nuget.org/v3/index.json
      working-directory: ./src
    
